02 server post
js-tasks-ru/nodejs-20210618_mikulich-siarhei pull request #7
Opened 2021-07-20 20:02 UTC by s-mikulich

2021-07-20 20:03 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-07-20 23:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-21 18:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2021-07-25 14:39 UTC, tadjik1 commented on 05-http-server-streams/01-file-server-get/server.js
> +    chunks.push(chunk);
несмотря на то, что тут и правда используются стримы - решение неверное. дело в том, что мы здесь не должны собирать чанки данных в памяти, мы должны их отдавать клиенту как можно быстрее. в этом видео я разбираю этот пример подробнее: https://www.youtube.com/watch?v=vDgoDE0NucA

2021-07-25 14:40 UTC, tadjik1 requested changes
@s-mikulich  второе задание выполнено блестяще! а по первому у меня есть замечания :)

2021-07-27 17:36 UTC, s-mikulich commented on 05-http-server-streams/01-file-server-get/server.js
> +    chunks.push(chunk);
Спасибо! :)
Заменил на pipe()
https://github.com/js-tasks-ru/nodejs-20210618_mikulich-siarhei/pull/7/files#diff-4d2e8d173d908c34bf9c660091a18e040415383f22e9ed73957f496aa810d25aR18

2021-07-27 18:14 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-07-27 23:35 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-30 15:06 UTC, tadjik1 approved these changes
@s-mikulich  очень красивое решение 👍

2021-07-30 15:07 UTC, merged